name: assignment-autotest-test
on: [push, pull_request]

jobs:
  test:
    container: cuaesd/aesd-autotest:unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ruby

      - name: Run unit test
        run: ./full-test.sh

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: path/to/test-results

